version: "1.0"
services:
  xero:
    image: jaypeng2015/show-me-the-money:latest
    ports:
      - '3000:3000'
  react:
    build: ./xero-ui
    container_name: xero-ui-container
    ports:
      - '4200:4200'
    networks:
      - xero_network
  node:
    build: ./xero-api
    container_name: xero-server-container
    ports:
      - '4000:4000'
    networks:
      - xero_network
    stdin_open: true
networks:
  xero_network:
    external: true
    name: xero-final_default